name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Artifact cache
        uses: Swatinem/rust-cache@v1

      - name: Check fmt
        run: make fmt-check

      - name: Run linter
        run: make linter

      - name: Run checks
        run: make check

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Run tests
        run: make test
