name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check fmt
        run: make fmt-check

      - name: Run linter
        run: make linter

      - name: Run checks
        run: make check

      - name: Run tests
        run: make test
